// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXyg-avp3-_KJ9mGzPS6PM9Vzse3AR0ws',
    appId: '1:455221731717:android:9326169d49f47034f364ec',
    messagingSenderId: '455221731717',
    projectId: 'test-732f2',
    databaseURL: 'https://test-732f2-default-rtdb.firebaseio.com',
    storageBucket: 'test-732f2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ3TynJGflB0ek11ytLmtWvDC9JtwIbTY',
    appId: '1:455221731717:web:0f5fdbf36d074237f364ec',
    messagingSenderId: '455221731717',
    projectId: 'test-732f2',
    authDomain: 'test-732f2.firebaseapp.com',
    databaseURL: 'https://test-732f2-default-rtdb.firebaseio.com',
    storageBucket: 'test-732f2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYh9N0SgREX2RYjb0Bu9DVEDjMftPJ9WU',
    appId: '1:455221731717:ios:bcc589dc681aa8b9f364ec',
    messagingSenderId: '455221731717',
    projectId: 'test-732f2',
    databaseURL: 'https://test-732f2-default-rtdb.firebaseio.com',
    storageBucket: 'test-732f2.firebasestorage.app',
    androidClientId: '455221731717-n17uken14jlgaef6sotuej401jj1un4k.apps.googleusercontent.com',
    iosClientId: '455221731717-m0jqkjlss40jnhoa2olhqhgcuqnjgump.apps.googleusercontent.com',
    iosBundleId: 'com.example.settleupLite',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYh9N0SgREX2RYjb0Bu9DVEDjMftPJ9WU',
    appId: '1:455221731717:ios:bcc589dc681aa8b9f364ec',
    messagingSenderId: '455221731717',
    projectId: 'test-732f2',
    databaseURL: 'https://test-732f2-default-rtdb.firebaseio.com',
    storageBucket: 'test-732f2.firebasestorage.app',
    androidClientId: '455221731717-n17uken14jlgaef6sotuej401jj1un4k.apps.googleusercontent.com',
    iosClientId: '455221731717-m0jqkjlss40jnhoa2olhqhgcuqnjgump.apps.googleusercontent.com',
    iosBundleId: 'com.example.settleupLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ3TynJGflB0ek11ytLmtWvDC9JtwIbTY',
    appId: '1:455221731717:web:0f5fdbf36d074237f364ec',
    messagingSenderId: '455221731717',
    projectId: 'test-732f2',
    authDomain: 'test-732f2.firebaseapp.com',
    databaseURL: 'https://test-732f2-default-rtdb.firebaseio.com',
    storageBucket: 'test-732f2.firebasestorage.app',
  );

}